VM_Orchestrator/VM_Orchestrator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('VM_OrchestratorApp.urls')),
    path('admin/', admin.site.urls),
]

VM_Orchestrator/VM_OrchestratorApp/urls.py
from django.urls import path

from VM_OrchestratorApp import views

app_name = 'VM_OrchestratorApp'
urlpatterns = [
    # API
    path('start_recon/', views.run_recon_against_target, name='start_recon'),
    path('approve_resources/', views.approve_resources, name='approved_scan'),
    path('update_elasticsearch/', views.force_update_elasticsearch, name='update_elasticsearch'),
    path('update_elasticsearch_logs/', views.force_update_elasticsearch_logs, name='update_elasticsearch_logs'),
    path('sync_redmine/', views.force_redmine_sync, name='sync_redmine'),
    path('add_code_vulnerability/', views.add_code_vuln, name='add_code_vulnerability'),
    path('rcv_code_vulnerability_state/', views.rcv_code_vuln_state, name='rcv_code_vulnerability_state'),
    path('add_web_vulnerability/', views.add_web_vuln, name='add_web_vulnerability'),
    path('run_module/', views.run_specific_module, name='run_module'),
    path('on_demand_scan/', views.on_demand_scan, name='on_demand_scan'), ## ON DEMAND
    # Views
    path('', views.index, name='index'),
    path('test_html/', views.test_html, name='test_html'),
    #
    path('current_resources/', views.current_resources, name='current_resources'),
    path('new_resource/', views.new_resource, name='new_resource'),
    path('approve_resource_beta/', views.approve_resources_beta, name='approve_resources'),
    path('current_vulnerabilities/', views.current_vulnerabilities, name='current_vulnerabilities'),
    path('current_observations/', views.current_observations, name='current_observations'),
    path('current_observations/<str:mongo_id>/', views.specific_observation, name='specific_observation'),
    path('web_vulnerabilities/', views.web_vulnerabilities, name='web_vulnerabilities'),
    path('infra_vulnerabilities/', views.infra_vulnerabilities, name='infra_vulnerabilities'),
    path('code_vulnerabilities/', views.code_vulnerabilities, name='code_vulnerabilities'),
    path('new_vulnerability/', views.new_vulnerability, name='new_vulnerability'),
    #
    path('domains/', views.domains, name='domains')
]

VM_Orchestrator/VM_OrchestratorApp/models.py
from django.db import models

# Create your models here.

VM_Orchestrator/VM_OrchestratorApp/forms.py
from django import forms

SEVERITY_CHOICES_ENG = [
	('INFORMATIONAL', 'INFORMATIONAL'),
	('LOW', 'LOW'),
    ('MEDIUM', 'MEDIUM'),
    ('HIGH', 'HIGH'),
    ('CRITICAL', 'CRITICAL')
]

SEVERITY_CHOICES_SPA = [
	('INFORMATIONAL', 'INFORMATIONAL'),
	('BAJO', 'BAJO'),
    ('MEDIO', 'MEDIO'),
    ('ALTO', 'ALTO'),
    ('CRITICO', 'CRITICO')
]

class ObservationForm(forms.Form):
    description = forms.CharField(label='Description', required=True, widget=forms.Textarea(attrs={'rows':4, 'cols':40}))
    description_note = forms.CharField(label='Description Note', required=True, widget=forms.Textarea(attrs={'rows':4, 'cols':40}))
    implication = forms.CharField(label='Implication', required=True, widget=forms.Textarea(attrs={'rows':4, 'cols':40}))
    recommendation = forms.CharField(label='Recommendation', required=True, widget=forms.Textarea(attrs={'rows':4, 'cols':40}))
    recommendation_note = forms.CharField(label='Recommendation Notes', required=True, widget=forms.Textarea(attrs={'rows':4, 'cols':40}))
    #
    severity = forms.CharField(label='Severity', widget=forms.Select(choices=SEVERITY_CHOICES_SPA), required=True)

    def populate(self, mongo_obj):
        self.fields['description'].initial = mongo_obj['OBSERVATION']['TITLE']
        self.fields['description_note'].initial = mongo_obj['OBSERVATION']['NOTE']
        self.fields['implication'].initial = mongo_obj['IMPLICATION']
        self.fields['recommendation'].initial = mongo_obj['RECOMMENDATION']['TITLE']
        self.fields['recommendation_note'].initial = mongo_obj['RECOMMENDATION']['URLS']
        #
        choices = SEVERITY_CHOICES_ENG if mongo_obj['LANGUAGE'] == 'eng' else SEVERITY_CHOICES_SPA
        self.fields['severity'].widget.choices = choices

class ApproverForm(forms.Form):
    file = forms.FileField()

VM_Orchestrator/VM_OrchestratorApp/views.py
# pylint: disable=import-error
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

import VM_OrchestratorApp.tasks as tasks
import VM_OrchestratorApp.src.utils.mongo as mongo
import VM_OrchestratorApp.forms as available_forms

from VM_Orchestrator.settings import settings

from celery import chain
import json
from datetime import datetime, date

import VM_OrchestratorApp.src.task_manager as manager
from VM_OrchestratorApp.src.utils import utils

import VM_OrchestratorApp.tasks as tasks

### VIEWS ###
def index(request):
    return render(request, 'base.html')

def test_html(request):
    return render(request, 'testbase.html')

def current_resources(request):
    resources = mongo.get_all_resources()
    if request.method == 'POST':
        response = utils.get_resources_csv_file(resources)
        return response
    return render(request, 'database_resources.html', {'object_list': resources})

def new_resource(request):
    return JsonResponse({'order': 'new_resource. TODO'})

def approve_resources_beta(request):
    if request.method == 'POST':
        form = available_forms.ApproverForm(request.POST, request.FILES)
        if form.is_valid():
            manager.handle_uploaded_file(request.FILES['file'])
            return HttpResponseRedirect('/')
    else:
        form = available_forms.ApproverForm()
    return render(request, 'approve.html', {'form': form})

def current_observations(request):
    resources = mongo.get_all_observations(True)
    if request.method == 'POST':
        response = utils.get_observations_csv_file(resources)
        return response
    return render(request, 'observations.html', {'object_list': resources})

def specific_observation(request, mongo_id):
    resource = mongo.get_specific_observation(mongo_id)
    if request.method == 'POST':
        form = available_forms.ObservationForm(request.POST)
        if form.is_valid():
            mongo.update_observation(form.cleaned_data, resource)
            return redirect('/current_observations/')
    form = available_forms.ObservationForm()
    form.populate(resource)
    return render(request, 'specific_observation.html', {'form': form})
    
# Testing
def domains(request):
    resources = mongo.get_domains()
    return render(request, 'domains.html', {'object_list': resources})


def current_vulnerabilities(request):
    return render(request, 'vulns_type.html')

def web_vulnerabilities(request):
    resources = mongo.get_all_web_vulnerabilities()
    if request.method == 'POST':
        response = utils.get_web_vulnerabilities_csv_file(resources)
        return response
    return render(request, 'Vulnerabilities/web_vulns.html', {'object_list': resources})

def infra_vulnerabilities(request):
    resources = mongo.get_all_infra_vulnerabilities()
    if request.method == 'POST':
        response = utils.get_infra_vulnerabilities_csv_file(resources)
        return response
    return render(request, 'Vulnerabilities/infra_vulns.html', {'object_list': resources})
    
def code_vulnerabilities(request):
    resources = mongo.get_all_code_vulnerabilities()
    if request.method == 'POST':
        response = utils.get_code_vulnerabilities_csv_file(resources)
        return response
    return render(request, 'Vulnerabilities/code_vulns.html', {'object_list': resources})

def new_vulnerability(request):
    return JsonResponse({'order': 'new_vulnerability. TODO'})

'''
{
    "domain": example.com,
    "email": "example@example.com"
}
'''

@csrf_exempt
def run_recon_against_target(request):
    if request.method == 'POST':
        json_data = json.loads(request.body)
        manager.recon_against_target(json_data)
        message = 'Recon started against %s' % json_data['domain']
        return JsonResponse({'INFO': message})
    return JsonResponse({'ERROR': 'Post is required'})

@csrf_exempt
def approve_resources(request):
    if request.method == 'POST':
        json_data = json.loads(request.body)
        manager.approve_resources(json_data)
        return JsonResponse({'INFO': 'ACCEPTED'})
    return JsonResponse({'ERROR': 'Post is required'})

@csrf_exempt
def force_update_elasticsearch(request):
    if request.method == 'POST':
        manager.force_update_elasticsearch()
        return JsonResponse({'INFO': 'Updating elasticsearch'})
    return JsonResponse({'ERROR': 'Post is required'})

@csrf_exempt
def force_update_elasticsearch_logs(request):
    if request.method == 'POST':
        manager.force_update_elasticsearch_logs()
        return JsonResponse({'INFO': 'Updating elasticsearch logs'})
    return JsonResponse({'ERROR': 'Post is required'})

@csrf_exempt
def force_redmine_sync(request):
    if request.method == 'POST':
        manager.force_redmine_sync()
        return JsonResponse({'INFO': 'Synchronizing redmine'})
    return JsonResponse({'ERROR': 'Post is required'})

'''
{
  "Title": "Unrestricted Spring's RequestMapping makes the method vulnerable to CSRF attacks",
  "Description": "Tool title \n tool description",
  "Component": "src/main/java/org/owasp/webwolf/FileServer.java",
  "Line": 25,
  "Affected_code": "string",
  "Commit": "261283c",
 "Username": "username",
  "Pipeline_name": "name",
  "Language": "spa/eng",
  "Hash": "hash",
  "Severity_tool": "Severity"
}
'''

@csrf_exempt
def add_code_vuln(request):
    if request.method == 'POST':
        json_data = json.loads(request.body, strict=False)
        manager.add_code_vuln(json_data)
        return JsonResponse({'INFO': 'Adding code vuln', 'VULN': json_data})
    return JsonResponse({'ERROR': 'Post is required'})

@csrf_exempt
def add_web_vuln(request):
    if request.method == 'POST':
        json_data = json.loads(request.body)
        manager.add_web_vuln(json_data)
        return JsonResponse({'INFO': 'Adding web vuln', 'VULN': json_data})
    return JsonResponse({'ERROR': 'Post is required'})

@csrf_exempt
def rcv_code_vuln_state(request):
    if request.method == 'POST':
        json_data = json.loads(request.body)
        manager.rcv_code_vuln_state(json_data)
        return JsonResponse({'INFO': 'Processing vuln state', 'State': json_data})
    return JsonResponse({'ERROR': 'Post is required'})


### ON DEMAND SCAN APPROVED REQUESTS ###
'''
{
    "domain": "example.com",
    "target": ["https://example.com"] ["127.0.0.1"],
    "module_identifier": "header_module"
}
'''
# Scan to run only one module
@csrf_exempt
def run_specific_module(request):
    if request.method == 'POST':
        json_data = json.loads(request.body)
        manager.run_specific_module(json_data)
        return JsonResponse({'INFO': 'Running module %s against %s from domain %s' % (json_data['module_identifier'], json_data['target'], json_data['domain'])})
    return JsonResponse({'ERROR': 'Post is required'})
'''
Will run web and ip scans against https://example.com
{
    "domain": "example.com",
    "resource": "https://example.com/",
    "invasive_scans": false,
    "nessus_scan": false,
    "acunetix_scan": false,
    "type": "url",
    "priority": 1,
    "exposition": 0,
    "email": "example@example.com"
}
Will run ip scans against 127.0.0.1, if port 80 or 443 is open, web scans will be run
{
    "domain": "example.com",
    "resource": "127.0.0.1",
    "invasive_scans": false,
    "nessus_scan": false,
    "acunetix_scan": false,
    "type": "ip",
    "priority": 1,
    "exposition": 0,
    "email": "example@example.com"
}
Will run recon agains domain example.com, each of the subdomains found will be
subjected to web and ip scans if they are alive
{
    "domain": "example.com",
    "resource": "",
    "invasive_scans": false,
    "nessus_scan": false,
    "acunetix_scan": false,
    "type": "domain",
    "priority": 1,
    "exposition": 0,
    "email": "example@example.com"
}
'''

@csrf_exempt
def on_demand_scan(request):
    if request.method == 'POST':
        received_json_data=json.loads(request.body)
        if received_json_data['domain'] == "":
            return JsonResponse({'ERROR': 'Please provide a domain for tracking'})
        manager.on_demand_scan(received_json_data)
    return JsonResponse({'data':'Hi'})

VM_Orchestrator/VM_OrchestratorApp/templates/activos.html
<html>
<head>
<title>Deloitte</title>
<link rel="icon" href="/favicon.ico" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="css">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #000000;">
  <a class="navbar-brand" href="#">
    <img src="https://media-exp1.licdn.com/dms/image/C560BAQGJHYXy9e1rEg/company-logo_200_200/0?e=2159024400&v=beta&t=2cKY680FdJOpOvLbpZdvqrqUJUTb4qaNEVw_zrSaHhg" width="60" height="60" class="d-inline-block align-top" alt=""> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'VM_OrchestratorApp:dashboard_activo' %}">Activos<span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'VM_OrchestratorApp:dashboard_vuln' %}">Vulnerabilidades</a>
    </div>
</nav>
  <div> 
<iframe src="http://161.35.226.228:5601/app/kibana#/dashboard/f654c860-d01a-11ea-83d1-edeee3756359?embed=true&_g=(filters%3A!()%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-1y%2Cto%3Anow))" height="100%" width="100%"></iframe>
  </div>
</body> 
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>

<html><head><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8"><meta name="Robots" content="NOINDEX " /></head><body></body>
                <script type="text/javascript">
                 var gearPage = document.getElementById('GearPage');
                 if(null != gearPage)
                 {
                     gearPage.parentNode.removeChild(gearPage);
                     document.title = "Error";
                 }
                 </script>
                 </html>

VM_Orchestrator/VM_OrchestratorApp/templates/base.html
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-teal.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
<body>

<div class="w3-bar w3-theme">
  <div class="w3-dropdown-hover">
  <button class="w3-button w3-theme">Resources<i class="fa fa-caret-down"></i></button>
    <div class="w3-dropdown-content w3-bar-block w3-border">
      <a href="{% url 'VM_OrchestratorApp:current_resources' %}" class="w3-bar-item w3-button">Found Resources</a>
      <a href="{% url 'VM_OrchestratorApp:approve_resources' %}" class="w3-bar-item w3-button">Approve Resources</a>
      <a href="{% url 'VM_OrchestratorApp:new_resource' %}" class="w3-bar-item w3-button">New Resource</a>
    </div>
  </div>
  <div class="w3-dropdown-hover">
  <button class="w3-button w3-theme">Vulnerabilities<i class="fa fa-caret-down"></i></button>
    <div class="w3-dropdown-content w3-bar-block w3-border">
      <a href="{% url 'VM_OrchestratorApp:current_vulnerabilities' %}" class="w3-bar-item w3-button">Found vulnerabilities</a>
      <a href="{% url 'VM_OrchestratorApp:new_vulnerability' %}" class="w3-bar-item w3-button">New Vulnerability</a>
    </div>
  </div>
  <a href="{% url 'VM_OrchestratorApp:current_observations' %}" class="w3-bar-item w3-button">Observations</a>
</div>

<!-- Header -->
<header class="w3-container w3-theme w3-padding" id="myHeader">
  <div class="w3-center">
  <h1 class="w3-xxxlarge w3-animate-bottom">VM-Orchestrator</h1>
  </div>
</header>

<!-- Script for Sidebar, Tabs, Accordions, Progress bars and slideshows -->
<script>
// Side navigation
function w3_open() {
  var x = document.getElementById("mySidebar");
  x.style.width = "100%";
  x.style.fontSize = "40px";
  x.style.paddingTop = "10%";
  x.style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}

// Tabs
function openCity(evt, cityName) {
  var i;
  var x = document.getElementsByClassName("city");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  var activebtn = document.getElementsByClassName("testbtn");
  for (i = 0; i < x.length; i++) {
    activebtn[i].className = activebtn[i].className.replace(" w3-theme-dark", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " w3-theme-dark";
}

var mybtn = document.getElementsByClassName("testbtn")[0];
mybtn.click();

// Accordions
function myAccFunc(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}

// Slideshows
var slideIndex = 1;

function plusDivs(n) {
  slideIndex = slideIndex + n;
  showDivs(slideIndex);
}

function showDivs(n) {
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = x.length} ;
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";  
  }
  x[slideIndex-1].style.display = "block";  
}

showDivs(1);

// Progress Bars
function move() {
  var elem = document.getElementById("myBar");   
  var width = 1;
  var id = setInterval(frame, 10);
  function frame() {
    if (width == 100) {
      clearInterval(id);
    } else {
      width++; 
      elem.style.width = width + '%'; 
      elem.innerHTML = width * 1  + '%';
    }
  }
}
</script>

</body>
</html>

VM_Orchestrator/VM_OrchestratorApp/templates/observations.html
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-teal.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
<body>
<div class="w3-container">
  <hr>
  <div class="w3-center">
      <!---
    <h2>Tables</h2>
    <p w3-class="w3-large">Don't worry. W3.CSS takes care of your tables.</p>
    --->
  </div>
    <form method="POST" class="post-form">{% csrf_token %}
        <div class="w3-container">
            <button class="w3-btn w3-theme" type="submit">Download csv file</button>
        </div>
    </form>
<div class="w3-responsive w3-card-4">
<table class="w3-table w3-striped " border="1px solid black" style="border: 1px solid black">
<thead>
	<tr class="w3-theme">
        <th rowspan="2" style="text-align:center; vertical-align:middle">Language</th>
        <th rowspan="2" style="text-align:center; vertical-align:middle">Title</th>
        <th colspan="2" style="text-align:center; vertical-align:middle">Observation</th>
        <th rowspan="2" style="text-align:center; vertical-align:middle">Implication</th>
        <th colspan="2" style="text-align:center; vertical-align:middle">Recommendation</th>
        <th rowspan="2" style="text-align:center; vertical-align:middle">Severity</th>
	</tr>
	<tr class="w3-theme">
        <th style="text-align:center; vertical-align:middle">Title</th>
        <th style="text-align:center; vertical-align:middle">Note</th>
        <th style="text-align:center; vertical-align:middle">Title</th>
        <th style="text-align:center; vertical-align:middle">URLs</th>
	</tr>
</thead>
<tbody>
    <ul>
        {% for resource in object_list %}
            <tr>
                <td>{{ resource.LANGUAGE }}</td>
                <td>
                  <a href="{% url 'VM_OrchestratorApp:specific_observation' resource.id %}">
                    {{ resource.TITLE }}
                  </a>
                </td>
                <td>{{ resource.OBSERVATION.TITLE }}</td>
                <td>{{ resource.OBSERVATION.NOTE }}</td>
                <td>{{ resource.IMPLICATION }}</td>
                <td>{{ resource.RECOMMENDATION.TITLE }}</td>
                <td>{{ resource.RECOMMENDATION.URLS }}</td>
                <td>{{ resource.SEVERITY }}</td>
            </tr>
        {% endfor %}
    </ul>
</tbody>
</table>
</div>

<!-- Script for Sidebar, Tabs, Accordions, Progress bars and slideshows -->
<script>
// Side navigation
function w3_open() {
  var x = document.getElementById("mySidebar");
  x.style.width = "100%";
  x.style.fontSize = "40px";
  x.style.paddingTop = "10%";
  x.style.display = "block";
}
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}

// Tabs
function openCity(evt, cityName) {
  var i;
  var x = document.getElementsByClassName("city");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  var activebtn = document.getElementsByClassName("testbtn");
  for (i = 0; i < x.length; i++) {
    activebtn[i].className = activebtn[i].className.replace(" w3-dark-grey", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " w3-dark-grey";
}

var mybtn = document.getElementsByClassName("testbtn")[0];
mybtn.click();

// Accordions
function myAccFunc(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

// Slideshows
var slideIndex = 1;

function plusDivs(n) {
  slideIndex = slideIndex + n;
  showDivs(slideIndex);
}

function showDivs(n) {
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length} ;
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  x[slideIndex-1].style.display = "block";
}

showDivs(1);

// Progress Bars
function move() {
  var elem = document.getElementById("myBar");
  var width = 5;
  var id = setInterval(frame, 10);
  function frame() {
    if (width == 100) {
      clearInterval(id);
    } else {
      width++;
      elem.style.width = width + '%';
      elem.innerHTML = width * 1  + '%';
    }
  }
}
</script>

</body>
</html>

VM_Orchestrator/VM_OrchestratorApp/templates/vulns_type.html
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-teal.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
<body>

<div class="w3-half">
<div class="w3-card-4 w3-container">
<h2>Vulnerabilities</h2>
<ul class="w3-ul w3-margin-bottom">
  <ul>
    <li><a href="{% url 'VM_OrchestratorApp:web_vulnerabilities' %}">Web vulnerabilities</a></li>
    <li><a href="{% url 'VM_OrchestratorApp:infra_vulnerabilities' %}">Infra vulnerabilities</a></li>
    <li><a href="{% url 'VM_OrchestratorApp:code_vulnerabilities' %}">Code vulnerabilities</a></li>
  </ul>
</ul>
</div>
</div>

<!-- Script for Sidebar, Tabs, Accordions, Progress bars and slideshows -->
<script>
// Side navigation
function w3_open() {
  var x = document.getElementById("mySidebar");
  x.style.width = "100%";
  x.style.fontSize = "40px";
  x.style.paddingTop = "10%";
  x.style.display = "block";
}
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}

// Tabs
function openCity(evt, cityName) {
  var i;
  var x = document.getElementsByClassName("city");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  var activebtn = document.getElementsByClassName("testbtn");
  for (i = 0; i < x.length; i++) {
    activebtn[i].className = activebtn[i].className.replace(" w3-dark-grey", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " w3-dark-grey";
}

var mybtn = document.getElementsByClassName("testbtn")[0];
mybtn.click();

// Accordions
function myAccFunc(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

// Slideshows
var slideIndex = 1;

function plusDivs(n) {
  slideIndex = slideIndex + n;
  showDivs(slideIndex);
}

function showDivs(n) {
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length} ;
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  x[slideIndex-1].style.display = "block";
}

showDivs(1);

// Progress Bars
function move() {
  var elem = document.getElementById("myBar");
  var width = 5;
  var id = setInterval(frame, 10);
  function frame() {
    if (width == 100) {
      clearInterval(id);
    } else {
      width++;
      elem.style.width = width + '%';
      elem.innerHTML = width * 1  + '%';
    }
  }
}
</script>

</body>
</html>